### ISSUE TITLE
 vista JobCompleted. 

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#106]
Debe parecerse a la vista WorkMode, que se vea como esa, con esa data, pero solo ahi es para Hacer Review
o en caso de que ya hiciste el Review, te debe salir el Review

<img width="442" alt="Screen Shot 2019-06-07 at 12 32 39 PM" src="https://user-images.githubusercontent.com/38106497/59119574-2a699780-8921-11e9-852b-d2cea8d9ae4b.png">

**Comment by alesanchezr** [comment]
tambien tienen que asegurarse que el Amount y total hours e calcule, ahora mismo se queda en cero

**Comment by pamelagbl** [comment]
@rich-97 la vista luego del review salecomo Job Details y debería ser Job Completed para cerrar.

**Comment by rich-97** [comment]
@pamelagbl cambio Job Details por Job Completed en esa vista?

**Comment by pamelagbl** [comment]
> @pamelagbl cambio Job Details por Job Completed en esa vista?

Si, cuando el trabajó se completó se hizo el rate y todo debería decir Job Completed
