### ISSUE TITLE
Cambiar mensaje de clock in

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#107]
el mensaje de Clockin in 12341234 minutes, debemos cambiar el numero, si es mas de 59 que lo diga en horas, y si es mas de 23 horas que lo diga en dias

**Comment by pamelagbl** [comment]
![Screenshot_20190620-170719](https://user-images.githubusercontent.com/38106497/59884526-41c36e80-937e-11e9-89cb-2c8ec515a300.png)

![Screenshot_20190620-171323](https://user-images.githubusercontent.com/38106497/59884803-fc537100-937e-11e9-9218-7f88dce2b780.png)

solo muestran las horas, no días.

@rich-97 @alacret

**Comment by pamelagbl** [comment]
@rich-97 y esto?

**Comment by pamelagbl** [comment]
ok @rich-97 el mensaje cambió pero muestra por ejemplo el caso de días 2.52 días

**Comment by rich-97** [comment]
@pamelagbl como debería de decir?

2 días y 12 horas así?

**Comment by pamelagbl** [comment]
> @pamelagbl como debería de decir?
> 
> 2 días y 12 horas así?

si @rich-97
