### ISSUE TITLE
My Availability: Json parse error: keyerror

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#108]
**Describe the bug**

**To Reproduce**
1. Go to 'My avalaibility'
2. Click on 'or specific time'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![IMG_0842 1](https://user-images.githubusercontent.com/38106497/59121559-63583b00-8926-11e9-97fc-13e7164d8e51.PNG)

**Comment by alesanchezr** [comment]
aqui lo que pasa es que no deja colocar un `specific time`

**Comment by rich-97** [comment]
@alesanchezr me puedes especificar por aca que debo enviar en ese endpoint?
