### ISSUE TITLE
Prioridades

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#109]
Lista de actividades a realizar para la entrega que se debe realizar el dia martes.

- [x] Verificar funcionamiento del login.
- [x] Verificar funcionamiento del registro de usuario.
- [x] Validar el email.
- [x] Verificar funcionamiento del recovery password.
- [x] Aceptar/rechazar invitaciones de trabajo.
- [x] Detalle de trabajo, verificar funcionamiento clock in y clock out.
- [x] Perfil de usuario.
- [x] Estandarizar las pantallas: tamaño de letra, tipo de letra, margenes, colores.
- [x] Mejoras en diseño.
- [x] Jobs preferences, bug my availability
- [x] Review Employer, ver los revies que se han hecho.

@rich-97 debemos trabajar en estas prioridades, que todo este funcionando bien para la entrega.

**Comment by alesanchezr** [comment]
@pamelagbl hay una version nueva de la app, podemos volver a probar todo esto?
