### ISSUE TITLE
No se puede valorar un employeer

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#113]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Image-1 (8)](https://user-images.githubusercontent.com/38106497/59224189-cef70e00-8b9b-11e9-8a4c-515cba114c8d.jpg)

**Comment by rich-97** [comment]
@pamelagbl después del cambio de @alacret logre valorar un employeer vuelve a probar y me dices.
