### ISSUE TITLE
Centrar el texto que contiene el boton de review employeer 

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#114]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Image-1 (7)](https://user-images.githubusercontent.com/38106497/59224238-f057fa00-8b9b-11e9-9741-93b6533a3847.jpg)

**Comment by rich-97** [comment]
@pamelagbl en Android se ve centrado, puedes probar de nuevo, revise los estilos y tiene el `text-align: center`.
