### ISSUE TITLE
workmode  debe actualizarce cada 1 segundo

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#115]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pamelagbl** [comment]
@rich-97 @alacret como verifico esto?

**Comment by alacret** [comment]
@pamelagbl ve si los minutos van cambiando y la barra de progreso avanza

**Comment by pamelagbl** [comment]
Earnings y horas completed van cambiando, la barra de progreso tambien avanza
