### ISSUE TITLE
El boton de clockin no esta tomando en cuenta el delta de clockin

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#119]
Si un shift empieza en 20 minutos, pero el company `maximum_clockin_delta_minutes` es 20 minutos, entonces ya el boton deberia dejarme hacer clockin

**Comment by rich-97** [comment]
@alacret @alesanchezr en el código esta bien la validación.

Revisar `job-utils.js` linea **29**.

**Comment by pamelagbl** [comment]
como debería verificar esto? @rich-97 @alacret

**Comment by alacret** [comment]
@pamelagbl 1 puedes hacer clockin 20 min (detlta) antes de la hora

**Comment by pamelagbl** [comment]
> @pamelagbl 1 puedes hacer clockin 20 min (detlta) antes de la hora

No, elboton apreció justo 15 minutos antes de comenzar
