### ISSUE TITLE
La vista de pauyments ahora dice un error "Already read" y no muetra los payments

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#124]
![Image from iOS (1)](https://user-images.githubusercontent.com/426452/59527453-9dd35200-8ea9-11e9-9099-512af1e0988b.png)

**Comment by rich-97** [comment]
@alesanchezr el endpoint de pagos no esta respondiendo bien, te muestro que esta respondiendo.

Request: `/employees/me/payroll-payments?status=PENDING`

```
ImproperlyConfigured at /api/employees/me/payroll-payments
Field name `rating` is not valid for model `Position`.
````
