### ISSUE TITLE
Arreglar logos en las pantallas de detalles

### ISSUE THREAD

**Issue by alacret** [JobCore/employee-mobile#125]
Aun se esta viendo el gallo, y no el logo de la empresa:

- [x] Invitation Details

![Simulator Screen Shot - IPhone 8 - 2019-06-14 at 13 47 19](https://user-images.githubusercontent.com/918895/59528010-2999ae00-8eab-11e9-9090-ea07d107eb8a.png)

- [x] JobCompleted

![Simulator Screen Shot - IPhone 8 - 2019-06-14 at 13 45 28](https://user-images.githubusercontent.com/918895/59528011-2999ae00-8eab-11e9-8569-695b3f62523d.png)

- [x] WorkMode

![Simulator Screen Shot - IPhone 8 - 2019-06-14 at 13 45 21](https://user-images.githubusercontent.com/918895/59528012-2999ae00-8eab-11e9-9808-8247f5b95a5d.png)

- [ ] Tambien en la vista de `ApplicationDetails.js`

**Comment by pamelagbl** [comment]
@rich-97 @alacret quizas sea en mi tlf pero no veo el logo de la empresa.

**Comment by alacret** [comment]
@rich-97
