### ISSUE TITLE
No se guarda los positions

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#130]
**Describe the bug**
Se intenta actualizar los position pero no se visualizan los cambios.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Job positions'
3. Scroll down to 'Cambiar o asignar job positions'

**Desktop (please complete the following information):**
 - OS: [Android]

**Smartphone (please complete the following information):**
 - Device: [ZTE]
 - OS: [Android 6.0]

**Comment by rich-97** [comment]
@pamelagbl estoy probando desde tu usuario y si se están guardando.

**Comment by pamelagbl** [comment]
pues yo cambios los positions y no se me guardan @rich-97

**Comment by rich-97** [comment]
@pamelagbl estas probando con el apk que te pase?

**Comment by pamelagbl** [comment]
> @pamelagbl estas probando con el apk que te pase?

con la mas reciente y sigue el problema

**Comment by alacret** [comment]
@rich-97 ?

**Comment by pamelagbl** [comment]
Con la version mas reciente sigue el problema en android @rich-97

**Comment by pamelagbl** [comment]
Me sigue pasando @rich-97
