### ISSUE TITLE
No se visualizan las imagenes de las empresas en la vista de Payments

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#131]
**Describe the bug**
No se visualiza las imagenes o logos de las empresas en el listado de Payments

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Payments'
3. Scroll down to 'Payments Pending'

**Screenshots**
![Screenshot_20190619-092751](https://user-images.githubusercontent.com/38106497/59778231-ba8dd200-927b-11e9-8c02-0f34ffd95f0a.png)

**Desktop (please complete the following information):**
 - OS: [Android]
 
**Smartphone (please complete the following information):**
 - Device: [ZTE Maven 2]
 - OS: [Android 6.0]

**Comment by rich-97** [comment]
Esa es la imagen/logo de la empresa **Fetes and Events** es lo que esta enviando Alejandro desde el backend.

**Comment by pamelagbl** [comment]
ok 

> Esa es la imagen/logo de la empresa **Fetes and Events** es lo que esta enviando Alejandro desde el backend.

ok.
