### ISSUE TITLE
My Jobs | Poner las columnas con un tamaño fijo para que no se deslineen

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#133]
**Describe the bug**
Los textos no se visualizan bien, se ven deslineados.

**To Reproduce**
1. Go to 'My Jobs'
2. Click on 'My Jobs -> list de jobs'
3. Scroll down to

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/38106497/59780073-04c48280-927f-11e9-9387-deef57c4edce.png)

**Desktop (please complete the following information):**
 - OS: [Android]
 
**Smartphone (please complete the following information):**
 - Device: [ZTE Maven 2]
 - OS: [Android 6.0]

**Comment by pamelagbl** [comment]
@alacret me ayudas en verificar esto en iphone?

**Comment by pamelagbl** [comment]
@alacret me ayudas a verificar en iOS?

**Comment by rich-97** [comment]
@pamelagbl @alacret no han podido probar en iphone?

**Comment by pamelagbl** [comment]
> @pamelagbl @alacret no han podido probar en iphone?

En android se ve bien, me apoyas en iphone? @alacret

**Comment by alacret** [comment]
@rich-97 @pamelagbl se ve bien por aqui
