### ISSUE TITLE
Onboarding view

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#134]
Realizar el diseño de las vistas faltantes para la app @ELM4RC0 

- [x] Profile
- [x] Preferences
- [x] Payments
- [x] My Jobs
- [x] Invitations
- [x] availablility

**Comment by pamelagbl** [comment]
Integrar diseño de las vistas onboarding

**Comment by rich-97** [comment]
@pamelagbl esto ya esta hecho.

**Comment by pamelagbl** [comment]
> @pamelagbl esto ya esta hecho.

todas las pantallas? Pero si estamos con el diseño???????

**Comment by rich-97** [comment]
> > @pamelagbl esto ya esta hecho.
> 
> todas las pantallas? Pero si estamos con el diseño???????

No, es decir, mi parte ya esta lista que es implementar ese endpoint en las vistas mencionadas.
