### ISSUE TITLE
Para seleccionar la "posicion" en job no esta como en el diseño

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#14]
![screen shot 2018-09-28 at 12 42 43 pm](https://user-images.githubusercontent.com/426452/46221675-109c9d00-c31c-11e8-80c1-d82a870ae292.png)

**Comment by alesanchezr** [comment]
Angel tuvo la idea de mover esto a una ventana separada, no me parece una mala idea. Conversenlo con el.

**Comment by pamelagbl** [comment]
Listo.
