### ISSUE TITLE
El dashboard no se esta actualizando

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#16]
![screen shot 2018-09-28 at 12 44 47 pm](https://user-images.githubusercontent.com/426452/46221751-5194b180-c31c-11e8-8ec9-b6ba571c53a5.png)

**Comment by pamelagbl** [comment]
En el dashboard no hemos trabajado aún, solo estamos mostrando el nombre de usuario. @alesanchezr
