### ISSUE TITLE
Select availability no esta ajustado al diseño

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#18]
![screen shot 2018-09-28 at 12 46 09 pm](https://user-images.githubusercontent.com/426452/46221827-843eaa00-c31c-11e8-85ac-14129f181606.png)

**Comment by alesanchezr** [comment]
Angel tuvo la idea de pasar esto a otra ventana tambien, no me parece mala idea.

Asi quedaria el diseño:

![screen shot 2018-09-28 at 1 06 06 pm](https://user-images.githubusercontent.com/426452/46222748-4abb6e00-c31f-11e8-810d-3824a1a789b1.png)

**Comment by alacret** [comment]
ajuste a las pantallas de preferencias:

- [ ]   POSITION:
1) Subtitulo "Position"
2) linea de texto centrado con la lista de posiciones activas separadas por coma
3) Boton Update Position, para abrir un modal con la lista de posiciones que se deben editar o que estan seleccionadas y se pueden de seleccionar, etc

- [] Availability: similar a Position
1) Subtitulo "Availability"
2) linea de texto centrado con la lista de dias (solo dias, no horas) activos separadas por coma
3) Boton Update Availability, para abrir un modal con la lista de opciones que se pueden editar o que estan seleccionadas y se pueden de seleccionar, etc

**Comment by pamelagbl** [comment]
Listo. @alesanchezr disponible versión 02-11
