### ISSUE TITLE
Icono de la aplicacion

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#19]
Crear el icono que va a salir en la aplicacion movil.

**Comment by pamelagbl** [comment]
@alesanchezr el icono debe ser 1024x1024 png sin transparencia.

**Comment by alesanchezr** [comment]
Te puedo pasar los editables para que tu lo saques de alli?

**Comment by pamelagbl** [comment]
@alesanchezr necesito algo así para el icono, no me sirvió ningún recurso que me compartiste
![image](https://user-images.githubusercontent.com/38106497/47660334-8d1dd800-db75-11e8-9f78-af9972a87566.png)
