### ISSUE TITLE
Validaciones en la vista de perfil

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#23]
- [x] Distancia: Maximo 100 millas, minimo 10 millas. Por defecto ponemos 50 millas.
- [x] Positions: No puedes no tener ningun cargo, y maximo puedes tener 5 cargos.
- [x] Minimum rate: Minimo 8 dolares maximo 60 dolares.
- [x] Auto apply esta apagado por defecto.
- [x] Dias de la semana: Tienes que tener al menos un dia habilitado para trabajar, si te vas a ir de vacaciones entonces puedes marcar el toggle que dice "stop receiving offers" q esta en el dashboard.

**Comment by pamelagbl** [comment]
@NodeJoSe para Jobs preferences tomar en cuenta

**Comment by alesanchezr** [comment]
Como se cierra este enhancement? ya yo termine mi parte. Si quieres sacame de los asignados @pamelagbl para no tenerlo entre mis todo.

**Comment by pamelagbl** [comment]
@NodeJoSe en la validación de position te esta indicando que al menos un cargo y máximo 5, cuando se va a actualizar y no se selecciona ningún cargo deja realizar el registro, cosa que no debería pasar debe mostrar un mensaje "al menos un cargo"

**Comment by pamelagbl** [comment]
@alesanchezr el toggle según se conversó lo hemos quitado. Este feature esta cerrado.
