### ISSUE TITLE
JOB DETAIL, detalles

### ISSUE THREAD

**Issue by alacret** [JobCore/employee-mobile#26]
- El mapa no sale centrado en el punto del Venue
- Debe salir un marker
- Que salga la direccion debajo del mapa, para que se pueda tocar para abrir Google Maps
- Controles en el Mapa
- En la vista de invitaciones debe salir un mensaje NO TIENES INVITACIONES en caso de que no existan

**Comment by alesanchezr** [comment]
@pamelagbl, @NodeJoSe  que ha pasado con esto??

**Comment by pamelagbl** [comment]
@alesanchezr en el diseño del no tiene ningunos controles, solo es para visualizar la localización, si se hace eso no se va a visualizar el mapa. Los jobs se deben crear siempre con su lat/lng, sino el mapa se mostrara por defecto en miami, como lo está haciendo en estos momentos, no se porque hay un problema con esto desde el web.

**Comment by alesanchezr** [comment]
yo se q es solo para visualizar, pero sia bueno poder controlar el zoom. Esto no es algo que a uds les toma timepo de arreglar porque es solo decir "show zoom controls" en el componente del mapa. Les toma 1 minuto.

Los jobs no tienen latlong, son las locations, y todas se crean con su latlong desde el principio. Mira este es un screenshot de la base de datos que te lo comprueba.

![screen shot 2018-11-05 at 12 15 19 pm](https://user-images.githubusercontent.com/426452/48014379-856dae80-e0f4-11e8-8ea3-4fa422dc78f4.png)

**Comment by alacret** [comment]
@alesanchezr ya esto esta listo
