### ISSUE TITLE
MY JOBS:  Desplegar detalles de  las applications, shift or invites

### ISSUE THREAD

**Issue by alacret** [JobCore/employee-mobile#27]
En el listado de Myjobs al tocar debe desplegar un modal con el detalle de la invitacion o el shift o el application segun sea el caso

**Comment by pamelagbl** [comment]
![image](https://user-images.githubusercontent.com/38106497/47235197-b0df6200-d3ae-11e8-83d7-41db6e8c3857.png)

**Comment by alacret** [comment]
Esto es lo que vanos reemplazar por una vista
