### ISSUE TITLE
Visualización de horas: se visualiza una hora menos en el dispositivo movil

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employee-mobile#31]
Shif creada a la hora correcta ![screenshot_4](https://user-images.githubusercontent.com/38106497/47582279-4f793f00-d92a-11e8-9169-cf05224905a4.png)

como se visualiza en el tlf

![img_0384](https://user-images.githubusercontent.com/38106497/47582475-d0d0d180-d92a-11e8-8f48-5b7715c53c7a.PNG)

**Comment by alesanchezr** [comment]
QUe paso con esto?

**Comment by pamelagbl** [comment]
bueno, quizás sea diferencia horaria. Pero si tu publicas una invitación para las 8pm debe visualizarse a las 8pm donde sea, sin importar lugar ni nada. @alesanchezr

**Comment by alesanchezr** [comment]
Dejame revisar esto, en realidad lo que deberia pasar es que te diga la hora en tu zona horaria. Si el shift es a las 8pm de Miami pero en CCS hay una hora menos, pues deberia decirte 7pm si estas en css. @alacret  que opinas tu?

**Comment by alacret** [comment]
@alesanchezr esto lo conversamos hace un par de semanas, tienes que guardar los datetime con la informacion del timezone, (django los guarda UTC siempre) para poder mostrarlos correctamente, si lo envias asi, se puede convertir

**Comment by alesanchezr** [comment]
@pamelagbl revise esto con angel y parece ser un problema en la aplicacion movil porque si se esta guardando con sin el timezone bien.

**Comment by pamelagbl** [comment]
@NodeJoSe

**Comment by alacret** [comment]
@alesanchezr ya esto esta listo
