### ISSUE TITLE
Guardar la locacion en el perfil del usuario

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#33]
En el profile del usuario hay un campo para latitud longitud, tenemos que guardar alli la locacion para que yo pueda enviar invitaciones solo de shifts que queden cerca de él.

**Comment by NodeJoSe** [comment]
Que es exatamente este campo y que restricciones tiene?

**Comment by alesanchezr** [comment]
En django es un decimal field:
```
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=0)
```
Lo que quiere decir que es un numero decimal y ya.

Un ejemplo de llamada seria:
```
PUT: /profiles/me

Body:
{
	"latitude":"25.744526",
	"longitude": "-80.260033"
}
```

**Comment by NodeJoSe** [comment]
Pero no entiendo, el usuario no va a tener esa data a mano

**Comment by alesanchezr** [comment]
@NodeJoSe en la vista donde ajustas tus preferencias, debajo de del slider donde ajustas el "maxium job distabce" tienes que poner un botton que diga "Location" y que diga tu locacion actual asi:

![screen shot 2018-11-05 at 12 10 55 pm](https://user-images.githubusercontent.com/426452/48014092-ea74d480-e0f3-11e8-8f8b-b3cd6977829c.png)

**Comment by alesanchezr** [comment]
@alacret bueno para el API es transparente, simplemente tendrias que colocar tu direccion manualmente y el mapa te muestra el marker para que ajustes pequeños detalles manualmente.

**Comment by pamelagbl** [comment]
@alesanchezr Ya este feature esta realizado, pero hay un problema con la api @NodeJoSe ya lo ha mencionado. No permite muchos decimales la latitud y longitud

**Comment by alesanchezr** [comment]
le meti 6 decimale mas, revisa si funciona. Django te obliga a poner un limite.

**Comment by NodeJoSe** [comment]
Me dio error con un location que tenia mas de 14 decimales

**Comment by alesanchezr** [comment]
Pero cuantos tenia?

**Comment by NodeJoSe** [comment]
Creo q esa no es la solución, pq si sale otro con mas decimales vamos a tener el mismo problema, estoy probando quitarle los decimales y al parecer no hay problema, creo q con 6 decimales es suficiente.

Puedes hacer el parsing en el server? para que lo ponga de 6 decimales antes de guardarlo? y le pones esa limitación a la BD si quieres, o es mejor que yo te lo envíe parseado?

**Comment by alesanchezr** [comment]
Buena idea, no se como no se me ocurrio antes, incluso creo q es justamente lo que yo hago en los venues y por eso me funciona.

Yo puedo hacerlo en el server pero nod hiper full con la logica de las notificaciones e implementado pruebas unitarias, hazlo tu por tu lado y yo lo hare mas adelante.

**Comment by alacret** [comment]
Cortale los decimales en el servicio, que asi si tenemos que tomar mas decimales es solo un cambio y deploy, y no hay que sacar una nueva version de la app @alesanchezr

**Comment by alacret** [comment]
@alesanchezr ya esto esta LISTO @NodeJoSe
