### ISSUE TITLE
Problemas en el mapa de la aplicacion movil

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#34]
- [x] En cualquier lugar donde salga un mapa en la applicacion de JobCore tiene que haber un boton para hacer zoom in y zoom out.
- [x] En los de talles de un trabajo el mapa no tiene marker.
- [x] Cuando ves el detalle de un application el mapa siempre aparece en el mismo lugar.

**Comment by pamelagbl** [comment]
@alesanchezr si, sale un mismo para todas las invitaciones es porque esta tomando el que colocamos por defecto, creo que reporte hace unas semanas ese problema que había al crear una nueva dirección.

**Comment by alacret** [comment]
Esto esta listo? @alesanchezr esto era con la API
