### ISSUE TITLE
Arreglos en la vista de preferencias de horario

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#36]
- [x] Cambia los dias de la semana a `Mon, Tue, Wed, Thu, Frid, Sat and Sun` para que la vista no se descuadre (fijate como el miercoles sobrepasa el lado derecho de la pantalla ahora mismo).
- [x] Habiamos hablado de que los saltos de minutos debian ser configurables en el componente de react, y por defect que saltara de 15min en 15 min.
- [x] Agrega un boton de `save and close`.

![img_0720](https://user-images.githubusercontent.com/426452/48012146-556fdc80-e0ef-11e8-9018-895e960fee64.jpg)

**Comment by pamelagbl** [comment]
@alesanchezr En el caso de wednesday que se sale del espacio, recuerda que se va a tomar el ancho de su contenido. Resulta que el nombre es largo, (nombre del día) + la hora tiene 12:00pm en cambio si colocas 2:00pm se ajusta a la pantalla.

**Comment by pamelagbl** [comment]
@alesanchezr podríamos realizar eso, de acortar los nombres y así esten ajustados a la pantalla.

**Comment by pamelagbl** [comment]
@alesanchezr ya esta listo, te explico unos detalles.

Esta vista tiene un autoguardado por asi decir, se va a guardar a medida que vayas presionando, porque es un listado, y se no puede guardar todo al mismo tiempo.

Otro punto acá con la otra tarea: @NodeJoSe me comentó que lo había conversado contigo en dejar esto como un time-select.

**Comment by NodeJoSe** [comment]
Ya esto lo habíamos conversado, dijimos que iba a ser como la vista de preferences, que se iban a hacer los cambios sin necesidad de un boton de save, ya que es un listado y sería mucho rollo un boton de save para guardar todo.

Sobre el timepicker, no es tan sencillo hacer los saltos de 15 minutos, si haces un listado con todas las horas sería demasiado grande, y sería mucho mas engorroso para seleccionarlo, creo q es mejor usar el timepicker del OS

**Comment by alesanchezr** [comment]
Pero ese timepicker de iOS no puede tener saltos mas grandes? 😮
