### ISSUE TITLE
No se muestra los detalles del employer en el listado de shift y detalles de shift

### ISSUE THREAD

**Issue by NodeJoSe** [JobCore/employee-mobile#41]
Hay alguna data que no se muestra en la app pq falta el employer en los listados y en el detalle de un shift, debes enviar la data del employer, ahorita solo esta llegando el id.

Las invitaciones y applications se muestran bien, falta arreglar los shift.

**Comment by alesanchezr** [comment]
ya lo agregue al detalle del shift, algun otro?

**Comment by NodeJoSe** [comment]
En el detalle y listado de shift

**Comment by NodeJoSe** [comment]
Revisa la api de shift, del listado pq esta dando error 500

**Comment by NodeJoSe** [comment]
Sigo sin ver los reviews y stars, no veo q este llegando la data

**Comment by alacret** [comment]
@NodeJoSe ya esto esta LISTO?

**Comment by alacret** [comment]
@alesanchezr
