### ISSUE TITLE
Upgrades on the user profile 

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#44]
- [ ] As a talent I need to be able to set a small description.
- [ ] Show the earned Badges
- [ ] Set picture.
- [ ] Show total rating and how many completed jobs.
- [ ] Show the 2 most recent reviews.

<p align="center">
<img height="500" src="https://user-images.githubusercontent.com/426452/48735686-0cec0f00-ec17-11e8-8660-de35aee8e893.jpg" />
</p>

**Comment by pamelagbl** [comment]
@alesanchezr Te comparto un boceto del Profile Public según los features que necesitan visualizarce y según lo que compartiste. Dinos que te parece.
![image](https://user-images.githubusercontent.com/38106497/48904746-20c58a00-ee3e-11e8-92b0-80944a27c1ae.png)

**Comment by pamelagbl** [comment]
@alesanchezr te comparto este otro boceto sobre el profile public. Estaremos atentos a las observaciones.
![image 1](https://user-images.githubusercontent.com/38106497/48954040-a1f84c00-ef26-11e8-9b07-6cccdca4c98a.png)

**Comment by ELM4RC0** [comment]
![profile](https://user-images.githubusercontent.com/11633792/50286649-70e03e00-0436-11e9-9e45-e40551832c58.jpg)

**Comment by mayecham** [comment]
Fue cerrado por error @alesanchez revisa los bocetos por favor. Para segui avanzando

**Comment by alesanchezr** [comment]
Mis comentarios:

- Usaria la opcoin A en lugar de la B.
- Quotaría las rayas que separan las secciones. 
- La zona de "reviews" en realidad es "What employers are saying about you"
- La barra de abajo de los iconos porque desaparecio?
- Como hago para volver al dashboard o a cualquier lado?
- Que paso con el boton de settings que habia arriba a la izquierda?

**Comment by alesanchezr** [comment]
@mayecham @ELM4RC0

**Comment by ELM4RC0** [comment]
![profile](https://user-images.githubusercontent.com/11633792/50346542-12d05b00-0509-11e9-8340-ac0c3d1e5523.jpg)

**Comment by alesanchezr** [comment]
- Los titulos "Badges" y "What employers are saying..." tienen la tipografia muy grande. Los titulos tienen que caber en una sola linea.
- En lugar de `What employers are sying about you` puedes decir `What employers said about you`.
- Vamos a darle un poco mas de margen a cada seccion, estan muy pegadas.

**Comment by ELM4RC0** [comment]
![profile](https://user-images.githubusercontent.com/11633792/50351644-3bf8e780-0519-11e9-9d86-b942e7ea8876.jpg)

**Comment by alesanchezr** [comment]
listo
