### ISSUE TITLE
Cambiar el splash screen (animacion si es posible)

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#45]
Vamos a esperar a que @edcorbo nos entrege el nuevo spash  para proceder a cambiarlo.

**Comment by alesanchezr** [comment]
La opcion C esta muy bonita!

Le puedes poner algo que diga "Loading..."?

**Comment by ELM4RC0** [comment]
![splashscreen1-01](https://user-images.githubusercontent.com/11633792/50649471-563cb780-0f54-11e9-9e3f-7ddeb888dc2c.jpg)

**Comment by alesanchezr** [comment]
excelente.
