### ISSUE TITLE
Refrescamiento de iconos en toda la móvil.

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#46]
Los iconos actualmente están pixelados y algunos podrían mejorar.

Vamos a esperar a que @edcorbo nos pase los nuevos iconos para reemplazarlos.

Se le solicitaron en SVG y PNG.

**Comment by alesanchezr** [comment]
Ya no nos van a pasar los iconos, los tiene que hacer @ELM4RC0 @alacret

**Comment by ELM4RC0** [comment]
![iconos-s](https://user-images.githubusercontent.com/11633792/50600314-16f46500-0e87-11e9-8a12-2cded7627d42.jpg)

**Comment by alesanchezr** [comment]
No habia que hace run rediseño, solo vectorizar los iconos actuales que estan pixelados :S

De igual forma el estilo del APP es origami. Tiene que ser siempre muy muy sencillo porque el usuario de esta applicacion no entiende mucho de tecnologia y queremos generarle sensacion de que somos imples y faciles.

Los iconos que planteas estan muy arrechos, en particular la estrella me encanto, pero todos son mas complicados que los originales, si fuera a elegir algo me quedaria con una simpligicacion del Sketch C.

**Comment by ELM4RC0** [comment]
ok ya comprendo voy a vectorizar los iconos actuales

**Comment by ELM4RC0** [comment]
![iconos-03](https://user-images.githubusercontent.com/11633792/50605729-968b2f80-0e99-11e9-8490-11217d3b2fb5.jpg)

**Comment by alesanchezr** [comment]
Listo pasaselos a @NodeJoSe para que los reemplaze en la app
