### ISSUE TITLE
Reporte de pending payments

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#47]
En el dashboard hay una metrica de pending payments, si le das click te lleva a esta vista de `/pending-payments` donde debe salir en primer lugar cuando dinero te deben, y por cuantas horas y luego una lista de todos los pagos pendientes, cada pago debe decir 
```
Fetes & Events will pay you $20 for 2.25 hrs on May 30th, 2019 from 3:00pm to May 30th, 2019 from 5:20pm
```

**Comment by ELM4RC0** [comment]
![report](https://user-images.githubusercontent.com/11633792/50286693-940aed80-0436-11e9-95ec-66209e2040a6.jpg)

**Comment by mayecham** [comment]
Fue cerrado por error @alesanchez revisa los bocetos por favor. Para segui avanzando

**Comment by alesanchezr** [comment]
@ELM4RC0 @mayecham 

- Me gusta la opcion A pero con los logos de las empresas.
- Esta vista es solo para los pending payments, no para los ya procesados, el texto en cada pago debe ser: "Fetes & Events will pay you $145 for being a Kitchen Assistant from May 30th 3:00pm to May 30th 6:00pm"
- Es importante el juego de colores, durante toda la aplicacion el nombre de la empresa ha tenido un color, la fecha otro, el monto por hora otro, etc. Revisa la vista de invitaciones.
- En lugar de `Money` decir: `Pending Amount` y en lugar de `Hours` decir `Total Hours`. 
- Que paso con la barra de abajo y los botones en la barra de arriba?
- Las lineas separadoras completas hasta los lados, sin padding.

**Comment by ELM4RC0** [comment]
![pending](https://user-images.githubusercontent.com/11633792/50346501-eddbe800-0508-11e9-80b9-1a94e6cc82db.jpg)

**Comment by alesanchezr** [comment]
Lo unico que le haria es poner un background muy clarito a la primera seccion para diferenciarla de la lista de pagos pendientes.

**Comment by ELM4RC0** [comment]
![pending](https://user-images.githubusercontent.com/11633792/50351798-97c37080-0519-11e9-883d-966ed1ae5fe9.jpg)

**Comment by alesanchezr** [comment]
listo.
