### ISSUE TITLE
Reporte de reviews

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#48]
En el dashboard hay una metrica de ratings, si le das click te lleva a esta vista de `/ratings` donde debe salir en primer lugar cual es tu rating total y en cuantos trabajos, luego una lista de ratings ordenada del mas reciente al menos reciente y cada rating debe contener:

- [x] Compañia que te hizo el rating
- [x] Fecha
- [x] Total en estrellas
- [x] En que rol te estabas desempeñando (server, bartender, etc.)
- [x] Algun comentario

**Comment by ELM4RC0** [comment]
![report](https://user-images.githubusercontent.com/11633792/50286772-d0d6e480-0436-11e9-84ec-9732526f26fa.jpg)

**Comment by mayecham** [comment]
Fue cerrado por error @alesanchez revisa los bocetos por favor. Para segui avanzando

**Comment by alesanchezr** [comment]
@mayecham @ELM4RC0 
Principalmente la version A pero con los siguientes cambios:
- Que significa rol? Esa es la posicion? Ponle "Working as" al principio. E.j: Working as: Server, Working as: Kitchen Assistant, Working as: Floor Runner, etc.? Puedes mostrarlos con posiciones de la vida real?
- Me gusta que haya logo de la empresa como en la opcion B.
- Me gusta la proporcion de la tipografia de la opcion B.
- La fecha la pondria en la misma linea que el Rol o que los reviews para aprovechar mejor el espacio.
- Los comentarios del review los dejaria que ocupen toda la linea (incluso debjo del logo de la empresa).
- Que pasa si un review no tiene comentarios? Como se ve?

**Comment by ELM4RC0** [comment]
![report](https://user-images.githubusercontent.com/11633792/50346576-2aa7df00-0509-11e9-954f-1c2a0e044abb.jpg)

**Comment by alesanchezr** [comment]
- Al principio, en vez de rating pondria "Your Rating" y el titulo arriba en la barra es solo "Reviews"
- Se puede poner la parte inicial con un background gris muy clarito? Para q se diferencia de la lista de reviews.

De resto me gusta bastante.

**Comment by ELM4RC0** [comment]
![reporte de reviews -1](https://user-images.githubusercontent.com/11633792/50351719-68146880-0519-11e9-8aab-e18050e8a8d6.png)

**Comment by alesanchezr** [comment]
listo.

**Comment by pamelagbl** [comment]
@rich-97 no se visualiza el total del rating ni los job completados.

**Comment by pamelagbl** [comment]
@rich-97 @alacret @alesanchezr no puedo ver el total de rating.

**Comment by alacret** [comment]
@pamelagbl @alesanchezr resetio la base de datos. Haz u rating desde la web y deberias poder verlo

**Comment by pamelagbl** [comment]
Esperando poder visualizar correctamente el **Rating del usuario**
