### ISSUE TITLE
Detalles en la vista de invitations

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#52]
- [x] Remover el salto de linea entre el position y la fecha? Dice "Miami-Date Inc is looking for a Server... (salto de linea)... from sep 26"
- [x] En lugar de "is looking for a Server `on From` Sep 26" debria decir "is looking for a Server `from` Sep 26"
- [x] Las lines que separan cada invitaciones deberian ir desde el principio hasta el final, ahorita tienen como un margen blanco de ambos lado.

**Comment by alesanchezr** [comment]
Aqui lo unico que falta que no lo mencione es remover el `Inc` que sale en gris despues del nombre de la empresa.

**Comment by NodeJoSe** [comment]
Listo

**Comment by mayecham** [comment]
revisado closed Issues.
