### ISSUE TITLE
Detalles del detalle de invitacion

### ISSUE THREAD

**Issue by alacret** [JobCore/employee-mobile#53]
![file](https://user-images.githubusercontent.com/918895/50709015-5f9d5100-1034-11e9-8230-16babdc78895.jpg)

- Remover la seccion de arriba, la que tiene como una foto y el titulo
- quitar la linea tambien que viene despues
- Colocarle los margenes de arriba y abajo a todos los componentes que se ven muy pegados

**Comment by alesanchezr** [comment]
@ELM4RC0 @alacret El boton de "open direction" esta mal ubicado, se ve fuera de proporcion y rato. Puedes hacer 2 propuestas para mejorar esa funcionalidad? Al final lo que se quiere es que el usuario tenga la manera de abrir google maps con la direccion del lugar ya puesta.

**Comment by mayecham** [comment]
Listo.

**Comment by alesanchezr** [comment]
@mayecham Pero y las propuestas??? Se supone que @alacret  y yo ibamos a revisar propuestas de @ELM4RC0

**Comment by mayecham** [comment]
@alesanchezr  le notifico a marco y les aviso.

**Comment by alesanchezr** [comment]
Bueno ya vi como quedo, seria "open directions' en vez de "open direction" .. de igual forma para la proxima version lo terminamos de montar bien porque tambien quisiera que te permitiera elegir entre google maps o apple maps y vamos a tener q rediseñar muchas partes de la vista porque hay que agregarle varias cosas.
