### ISSUE TITLE
Diseñar los iconos de los siguientes badges

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#54]
Recuerda que el estilo de la aplicación es origami y muy simple. Nada de sobras o 3D.

Necesitamos diseñar los iconos de 5 badges para esta version, son los que van a ir en el perfil, tiene que notarse que son badges y no solo unos iconos allí flotando, tiene que poder diferenciarse de los otros iconos de la aplicación. Entregalos en PNG y SVG porfa, el tamaño puede ser `64px` x `64px`

Estos son los badges que tenemos que diseñar:

1. **English Proficient**: Que habla muy bien ingles. El icono puede ser algo relacionado con la bandera de USA.
2. **Spanish Proficient**: Que habla muy bien español, lo mismo que el de arriba pero con la bandera de España.
3. **Sharp Looking**: Es es muy elegante y arreglado. El icono podria ser una pajarita (bow tie) o un esmoquin.
4. **On Time**: Que siempre llega a tiempo a los trabajos. El icono podria ser un reloj.
5. **Responsive**: Que responde las invitaciones a tiempo. El icono podria ser el mismo icono de invitaciones pero con un relojito encima.

**Comment by alesanchezr** [comment]
@mayecham @ELM4RC0 que opinan?

**Comment by ELM4RC0** [comment]
![iconos-02](https://user-images.githubusercontent.com/11633792/50996129-8279aa80-14f7-11e9-8e1c-d7daa85e6097.jpg)

**Comment by alesanchezr** [comment]
me los pasas separados en png y on fondo transparente?

**Comment by ELM4RC0** [comment]
Alejandro los badges en 64x64 png fondo transparente
[https://drive.google.com/open?id=1ucB8AHU1Ve6lbY_w9yvEBqe0EOIbddU_](url)

**Comment by mayecham** [comment]
Cerramos este Issues y creare otro para la version 3. Donde sea colocar estos iconos.

**Comment by alesanchezr** [comment]
es q uds no tienen que colocar nada, eso llega por al API.
