### ISSUE TITLE
Pending Payments

### ISSUE THREAD

**Issue by alacret** [JobCore/employee-mobile#56]
![pp](https://user-images.githubusercontent.com/918895/50849303-9f21b100-1344-11e9-8db0-486aba08d2e8.jpg)

Modificaciones al Diseño:

- Antes del Header de la Vista (Donde esta pending payments) colo un SEGMENT de Native Base, para seleccionar si se van a ver PENDING Payments o PREVIOUS Payments. 
-

**Comment by alesanchezr** [comment]
@alacret mejor es que @ELM4RC0 haga una propuesta con esta modificacion.

Marco, queremos ahora agregar tambien la opcion de que puedas ver tus cobros que ya cobraste, entonces e nos ocurrio la idea de poner un toggle arriba de `pending amount` y `total hours` que te permita intercambier entre `Pending Payments` or `Cleared Payments`. El toggle es parecido al que veas en la vista de jobs que te permite cambiar entre pending, upcoming, etc...

Tambien hay que cambiar `Pending Amount` por solo `Amount` porque ese total va a cambiar segun si estas viendo los `Pending Payments` o `Cleared Payments`.

**Comment by ELM4RC0** [comment]
![pendingpayments](https://user-images.githubusercontent.com/11633792/51001381-46017b00-1506-11e9-82d6-28f5e261a872.jpg)

**Comment by ELM4RC0** [comment]
el titulo de esta vista debería cambiar a "**Payments**" porque se están unificando en una sola

**Comment by alesanchezr** [comment]
Si tienes razon, y me gusta el diseño, vamos a darle asi.

**Comment by pamelagbl** [comment]
@alacret no se ven las imagenes.
![Screenshot_20190619-092751](https://user-images.githubusercontent.com/38106497/59774446-14d76480-9275-11e9-8cc6-3a1f960289fd.png)

**Comment by pamelagbl** [comment]
solo falta el onboardin en esta vista.
