### ISSUE TITLE
Imagen por defecto cuando no se tienen imagen cargada

### ISSUE THREAD

**Issue by mayecham** [JobCore/employee-mobile#59]
No le pongas al perfil de usuario foto por defecto, jose ya lo esta haciendo. y si vas a poner una imagen por defecto envia una imagen png con la direccion completa. 
![image](https://user-images.githubusercontent.com/28816166/50856031-faad6800-135f-11e9-9dd3-b146972e8f72.png)

**Comment by alesanchezr** [comment]
Listo.
