### ISSUE TITLE
Corregir posición del marker de google maps

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#60]
Si haces `zoom in` o `zoom out` en el mapa te das cuenta que la punta inferior del marker se posiciona en otros lugares diferentes al original, mientras mas `zoom out` peor es el error.

Angel y yo creemos que esto se soluciona asi:
Hay que restarle la mitad de su height en la cordenada Y y la mitad de su width en la coordenada X

**Comment by NodeJoSe** [comment]
Hay q probar esto con una nueva version

**Comment by mayecham** [comment]
A mi me funciono bien. @alesanchezr  revisa y me comentas si no esta bien reabrir

**Comment by mayecham** [comment]
listo

**Comment by mayecham** [comment]
@NodeJoSe  revisemos esto cuanto antes. no dejemos nada de v2. Antes de comenzar la v3
