### ISSUE TITLE
Nueva vista para cambiar constraseña

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#62]
![img_0956](https://user-images.githubusercontent.com/426452/50924593-01021980-141e-11e9-81df-d008548579c0.jpg)

- [x] La vista deberia tener el mismo estilo de todas las demas, con el fondo blanco y la barra arriba que diga "Change you password".
- [x] En lugar del logo de JobCore que salga un mensaje que diga "Fill out your email address and we will send you and email with instructions to change your password".
- [x] El botón debe decir: "Send instructions"

**Comment by NodeJoSe** [comment]
Esta es la misma vista q estaba diseñada para cusndo no has hecho logout, pq hace exactamente lo mismo, tener 2 vistas diferentes seria mas confuso

**Comment by alesanchezr** [comment]
Entonces dejala asi y ponle el mensaje debajo del logo.

**Comment by mayecham** [comment]
realizado

**Comment by mayecham** [comment]
Se pasa para la V3 y se reabre. No se pueden seguir haciendo cambios en esta version.

**Comment by alesanchezr** [comment]
Esta vista es interna, por eos le estoy poiendo el tag de diseño para que marco le ponga un diseño diferente a "recordar contraseña" porque a pesar de que se parecen una es interna y la otra es externa.

**Comment by ELM4RC0** [comment]
![Change you password](https://user-images.githubusercontent.com/11633792/54840715-f5e02b00-4ca3-11e9-8995-ce7edd212fa4.png)

**Comment by alesanchezr** [comment]
@ELM4RC0 
- El texto grande debe decir CHANGE PASSWORD (TITULO) en vez de CHANGE YOUR PASSWORD
- El texto largo que esta ahorita, reducirle el tamano y el color a gris y colocarlo debajo del TITULO
- Recuerdal quitarle el icono de arriba a la derecha
- Arriba a la izquierda manten la X para salir, que asi lo hemos estado haciendo en todos lados

**Comment by ELM4RC0** [comment]
![Change password](https://user-images.githubusercontent.com/11633792/55265876-8690ab00-5250-11e9-8b88-6455065c7cef.png)
