### ISSUE TITLE
Colocar los nuevos Iconos para los Badges.

### ISSUE THREAD

**Issue by mayecham** [JobCore/employee-mobile#74]
Colocar los nuevos iconos diseñados por marco para los badges. 
Adjunto direccion: 
https://drive.google.com/open?id=1ucB8AHU1Ve6lbY_w9yvEBqe0EOIbddU_

**Comment by NodeJoSe** [comment]
Esto le corresponde a @alesanchezr debe agregar las images .png a los badges y poner el link en el campo "image_url" como habíamos quedado

**Comment by alesanchezr** [comment]
cierto. cerrado.
