### ISSUE TITLE
Mejoras a la vista de job

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#75]
- El boton de clockin siempre debe aparecer pero si todavia no puedes hacer clock debe decir “Clock In 1:30 min” y que vaya restandose con el tiempo.
- El talento debe poder revisar su historial (log) de checkins que ha hecho en un shift y ese botón solo debe aparecer en los shifts que trabajase.
- Si el shift ya paso debe salir cuantas horas trabaje y cuanto dinero me gane gracias a eso.

Recuerden pasar una propuesta visual antes de empezar a programar.

**Comment by ELM4RC0** [comment]
![Profile edit – 1](https://user-images.githubusercontent.com/11633792/55095566-babc6e00-508e-11e9-80b0-07227a4c128e.png)

**Comment by alesanchezr** [comment]
**NOTA IMPORTANTE : Porfavor vamos a usar datos reales en los diseño para que se parezcan a la vida real lo mas possible.**

VISTAS:
- JOB PENDIENTE: Es la vista del Job antes de comenzar el Shift. Es la vista de la izquierda.
- JOB TERMINADO: Es la vista del Job una vez se ejecuto el Shift, es la vista de la derecha

1) Descartamos la vista del centro, La historia de los clockins and clock outs se vera en la misa vista del JOB TERMINADOcomo esta en la imagen de la derecha

2) Correcciones a la Vista de JOB PENDIENTE:

- El diseño del area superior deberia tener fondo gris como todas las demas vistas, haz que el estilo se paresca.
- Que el nombre del employer y el job position se vean asi:
![Screen Shot 2019-03-28 at 11 51 26 AM](https://user-images.githubusercontent.com/426452/55172105-e2273f80-514f-11e9-960a-458f56e485f1.png)
- Tambien haria falta incluir la hora de inicio del shift, la fecha, el numero de horas a trabajar, hora de inicio y hora fin y cuando se paga por hora.
- Colocar el Mapa full Width, es decir que no tenga margeners con respecto a la vista principal
- Debe salir la direccion completa del trabajo debajo del mapa.
- Quita el boton de open direction, en lugar de eso pon la direccion subrayada para que el susuario sepa que le puede dar click.

3) Correcciones a la vista de JOB TERMINADO
- Necesitamos la informacion completa del JOB, Nombre del Lugar, Fecha inicio y Fin, precio por hora
- El are del Resumen (Area donde sale el total de dinero y horas): A) Reemplazar la palabra AMOUNT por ERANINGS
- Esta bien que el mapa no salga, pero si necesitamos la direccion clickeable como en la pantalla de JOB PENDIENTE

**Comment by ELM4RC0** [comment]
![Jobprefences](https://user-images.githubusercontent.com/11633792/55284317-3a259800-5342-11e9-9294-20fd511f2e50.jpg)

**Comment by alacret** [comment]
1. quitamos la seccion que llamanos HGEADER2 (Date, Time, address)
2. Mantenemos el Header3 (Earning, / Hours Completed)
3. Sin progress bar
4. El review: mantener el boton abajo, y agrgar un mensaje indicando que el usuario debe llenar el Review como lo que hicimos en JOB PREFERENCES:
![m7](https://user-images.githubusercontent.com/918895/56066456-cb830a00-5d45-11e9-8db7-3a93903c631f.png)

**Comment by ELM4RC0** [comment]
![Jobprefences](https://user-images.githubusercontent.com/11633792/56246335-bd97f680-606f-11e9-8d21-b93760db0645.jpg)
