### ISSUE TITLE
Mejoras en la vista de PERFIL PUBLICO

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#77]
- [x] Show percentage of completion and encourage the user to fill the entire profile, something like "Add a picture of yourself and talk about your experience to increase your visibility and receive more invites".

- [x] On edit profile say "What makes you a talent? Talk a little about your previous experience and skills"

- [x] If you don't have any ratings, instead of `N/A` say something like "No one has rated you yet" and The same in completed jobs.

- [x] If you have no ratings and jobs we have to encourage the user to start working. We can have a blinking questionmak `?` on top of the rating box and also the completed jobs box that you can click and explains how to get ratings and jobs.

**Comment by ELM4RC0** [comment]
![mejoras-en-la-vista-de-perfil-77](https://user-images.githubusercontent.com/11633792/51545189-d493c780-1e37-11e9-9882-bd8cf161bdfc.jpg)

**Comment by alesanchezr** [comment]
Ya no vamos a tener multiples signos de interrogacion, sino que esta pantalla va atener una ayuda similar a la de todas las demas, un solo signo de interrogacion que va a estar presente en toda la aplicacion en todas las pantalla que tengan ayuda, al hacerle click es que sale el carrusel.

**Comment by ELM4RC0** [comment]
![Profile public-2](https://user-images.githubusercontent.com/11633792/54869616-9f412280-4d71-11e9-96b5-5e5e6a53b014.png)

**Comment by alesanchezr** [comment]
Lo veo bien.

**Comment by alacret** [comment]
@alesanchezr que te parece quitar el icono de preferencias de ahi, y pasarlo a un boton, y dejar ese espacio arriba a la izquierda siempre para el signo de ayuda? para ser mas consistentes

**Comment by alesanchezr** [comment]
@ELM4RC0 ver observacion de #79 sobre quitar el icono de arriba a la derecha de preferencias y dejar solo el icono de signo de interrogacion

**Comment by ELM4RC0** [comment]
![Profile public-2](https://user-images.githubusercontent.com/11633792/55283988-ef088680-533b-11e9-8ef6-1e8f1fe75627.png)

**Comment by pamelagbl** [comment]
@alacret y @rich-97 quizas sea en mi tlf pero no visualizo el icono de signo de interrogacion en esta vista, o ya no va?

**Comment by alacret** [comment]
@pamelagbl creo que esta no, la de editar perfil si, correcto @alesanchezr  ?

https://jobcore.herokuapp.com/api/onboarding/views

**Comment by pamelagbl** [comment]
> @pamelagbl creo que esta no, la de editar perfil si, correcto @alesanchezr ?
> 
> https://jobcore.herokuapp.com/api/onboarding/views

yo creo que si va en la principal.

**Comment by pamelagbl** [comment]
Pendiente visualizar **Your rating** **Job Completes**
