### ISSUE TITLE
Mejoras en la vista de invitations

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#78]
mejorar el mensaje de NO INVITATIONS a:

```
You have no pending invitations.

The more flexible your job preferences are, the more invites you get, click here to update your preferences.
```

Y que salga un signo de interrogación que cuando lo apretas muestra un gif animado de como cambiar tus job preferences. (este gif animado lo vas a obtener de un endpoint).

Por otro lado, cuando hago APPLY o REJECT debería automáticamente actualizar la lista de INVITES.

**Comment by alacret** [comment]
![Screen Shot 2019-04-29 at 11 10 27 AM](https://user-images.githubusercontent.com/918895/56906015-6df1fb80-6a6f-11e9-94d3-5ea028e78ad4.png)

Pero con los botones de ACEPTAR Y RECHAZAR

**Comment by alacret** [comment]
Cerrada, es reemplaza por #87
