### ISSUE TITLE
Mejoras en la vista de job preferences

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#79]
## Mejoras propuestas:

1. El slider de seleccionar el rango de distancia solo debe aparecer si ya tenemos tu ubicacion. Sino la tenemos debe salir un asterisco rojo que titile encima del boton de "My Location"  que cuando lo apretes diga "Set your location to receive better job invitations." y muestre un pequeño gif animado de como hacerlo.
2. Tenemos que mostrar un warning al usuario si sus preferencias estan siendo demasiado exigentes o inflexibles, por ejemplo: Si solo quieres cobrar mas de 25 dolares la hora.

### Mas acerca del warning 
Este warning se puede eliminar, y solo aparece cuando acabas de modificar tus prefencias, si ya apareció y lo cierras no vuelve a salir hasta que vuelvas a modificar alguna de tus preferencias.

El warning debe salir si:
- El precio de hora es mayor a $25
- El radio de la distancia de trabajo es mejor a 15millas
- Si seleccionaste una sola job position.
- Si puedes trabajar solo dos o menos dias de la semana.
- Si en total pones menos de 10 horas de disponibilidad.

El warning debe decir: "Your job preferences might be to narrow, the more flexible you are the more job invites you will get"

**Comment by ELM4RC0** [comment]
![Jobprefencesset](https://user-images.githubusercontent.com/11633792/54957593-8aa78a80-4f29-11e9-83d8-7976c82075dd.jpg)

**Comment by alesanchezr** [comment]
Que pasa si hago click en ok? cuando volveria a salir? Hagamos ese warning dentro de la vista y no como una alerta para que podamos dejarlo fijo. Se puede?

**Comment by ELM4RC0** [comment]
![Job prefences-1 – 3](https://user-images.githubusercontent.com/11633792/55084151-1f6dcd80-507b-11e9-95d0-1aeda4d34eb9.png)

**Comment by alesanchezr** [comment]
@ELM4RC0 
- Quitemos de todas las pantallas lo que esta ocupando el puesto de arriba a la derecha en el header. Esta posicion sera ocupada por el signo de interrogacion de ayuda cuando este presente.
- Actualmente, para acceder al perfil, esta un icono arriba a la derecha, vamos a moverlo como una quinta opcion a la barra de abajo de navegacion

En esta pantalla:
- Los selectores solo estan mostrando el limte maximo posible, deberian tambien mostrar el limite minimo. Y el seleccionado deberia ser un poquito mas relevante
- El segundo selector es en metros, no en horas

**Comment by ELM4RC0** [comment]
![Jobprefences3](https://user-images.githubusercontent.com/11633792/55284276-583ec880-5341-11e9-865d-ec434d2a10e4.png)
