### ISSUE TITLE
Mejoras a la vista de invitacion

### ISSUE THREAD

**Issue by alesanchezr** [JobCore/employee-mobile#87]
![Imagen de iOS](https://user-images.githubusercontent.com/426452/55171720-3bdb3a00-514f-11e9-9a1f-78470fa5dd67.png)

**Comment by alesanchezr** [comment]
- Porfavor vamos a usar datos reales en los diseño para que se parezcan a la vida real lo mas possible.
- El diseño del area superior deberia tener fondo gris como todas las demas vistas, haz que el estilo se paresca.
- Que el nombre del employer y el job position se vea asi:
![Screen Shot 2019-03-28 at 11 51 26 AM](https://user-images.githubusercontent.com/426452/55172105-e2273f80-514f-11e9-960a-458f56e485f1.png)
- Tambien haria falta incluir la hora de inicio del shift, la fecha, el numero de horas a trabajar, hora de inicio y hora fin y cuando se paga por hora.
- Debe salir la direccion completa del trabajo, puede ser debajo del mapa.
- Quita el boton de open direction, en lugar de eso pon la direccion subrayada para que el susuario sepa que le puede dar click.

@alacret estamos tomando como referencia este estilo:
![Screen Shot 2019-03-28 at 11 59 11 AM](https://user-images.githubusercontent.com/426452/55172817-0afc0480-5151-11e9-9d98-b625f9b29a6c.png)

**Comment by ELM4RC0** [comment]
![invitacion](https://user-images.githubusercontent.com/11633792/55284066-53781580-533d-11e9-816a-b7a6ccb1e57e.png)

**Comment by alacret** [comment]
@ELM4RC0 

1. mantengamos el header con el icono, el nombre del employeer, el nombre del position (asi para todas las vistas)
2. La fecha y la hora vamos a colocarla mas parecido a las demas vistas:
![m2](https://user-images.githubusercontent.com/918895/56063960-bce52480-5d3e-11e9-87c2-a44d22ce0db3.png)
con esta info:
|        fecha      |     date  |
| --- | --- | 
| Feb 23 to Feb 24 | 3pm to 6pm |
| total hours |   total money:  |

3. direccion debajo del mapa, mas pequena y mas pegada al map
4. quitar linea
5. colocar botones con fondo de color solido

**Comment by ELM4RC0** [comment]
![invitacion](https://user-images.githubusercontent.com/11633792/56246656-92fa6d80-6070-11e9-9d3e-2127e272fa8b.png)
